blank_issues_enabled: false
contact_links:
  - name: General
    url: https://github.com/tensei-engine/.github/discussions/new?category=general
    about: Chat about anything and everything here
  - name: Ideas
    url: https://github.com/tensei-engine/.github/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Questions
    url: https://github.com/tensei-engine/.github/discussions/new?category=q-a
    about: Ask the community for help
