name: Create task
description: Create a task
body:
  - type: markdown
    attributes:
      value: ⚠️ Make sure to search for existing issues, discussions or pull requests before creating a new issue.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the chore is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the chore here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Related issues, discussions or pull requests
      description: Link to related issues, discussions or pull requests.
    validations:
      required: false
